import { getCloudflareContext } from "@opennextjs/cloudflare";

type D1Result<T> = { results?: T[] };
type D1Prepared = { bind:(...values:unknown[])=>D1Prepared; first:<T=unknown>()=>Promise<T|null>; all:<T=unknown>()=>Promise<D1Result<T>>; run:()=>Promise<unknown> };
type D1DatabaseLike = { prepare:(sql:string)=>D1Prepared };
type Env = { VIRA_DB?:D1DatabaseLike };

export type LeadRecord={id:number;created_at:string;updated_at:string;status:string;name:string;company:string;email:string;phone:string|null;service:string|null;budget:string|null;brief:string;notes:string};
export type CampaignRecord={id:number;name:string;created_at:string;client:string;objective:string;budget:string;status:string;start_date:string|null;end_date:string|null;notes:string;lead_id:number|null;creator_count:number;deliverable_count:number};
export type DeliverableRecord={id:number;campaign_id:number;creator_id:number|null;title:string;due_date:string|null;status:string;notes:string;creator_name:string|null};

export function getOpsDb(){try{const {env}=getCloudflareContext();return (env as unknown as Env).VIRA_DB??null}catch{return null}}
const clean=(v:unknown,max=2000)=>typeof v==='string'?v.trim().slice(0,max):'';

export async function saveLead(data:Record<string,unknown>){const db=getOpsDb();if(!db)return {saved:false as const,reason:'DB_NOT_CONFIGURED' as const};await db.prepare(`INSERT INTO leads (name,company,email,phone,service,budget,brief) VALUES (?,?,?,?,?,?,?)`).bind(clean(data.name,80),clean(data.company,120),clean(data.email,160),clean(data.phone,50),clean(data.service,120),clean(data.budget,80),clean(data.message,2000)).run();return {saved:true as const}}

export async function listLeads(){const db=getOpsDb();if(!db)return null;const r=await db.prepare(`SELECT * FROM leads ORDER BY datetime(created_at) DESC LIMIT 250`).all<LeadRecord>();return r.results??[]}
export async function updateLead(id:number,status?:string,notes?:string){const db=getOpsDb();if(!db)return false;const sets:string[]=[];const vals:unknown[]=[];if(status){sets.push('status = ?');vals.push(status)}if(typeof notes==='string'){sets.push('notes = ?');vals.push(notes.slice(0,5000))}if(!sets.length)return true;sets.push('updated_at = CURRENT_TIMESTAMP');vals.push(id);await db.prepare(`UPDATE leads SET ${sets.join(', ')} WHERE id = ?`).bind(...vals).run();return true}

export async function listCampaigns(){const db=getOpsDb();if(!db)return null;const r=await db.prepare(`SELECT s.*, COUNT(DISTINCT sc.creator_id) creator_count, COUNT(DISTINCT d.id) deliverable_count FROM shortlists s LEFT JOIN shortlist_creators sc ON sc.shortlist_id=s.id LEFT JOIN deliverables d ON d.campaign_id=s.id GROUP BY s.id ORDER BY datetime(s.created_at) DESC`).all<CampaignRecord>();return r.results??[]}
export async function createCampaign(data:Record<string,unknown>){const db=getOpsDb();if(!db)return false;await db.prepare(`INSERT INTO shortlists (name,client,objective,budget,status,start_date,end_date,notes,lead_id) VALUES (?,?,?,?,?,?,?,?,?)`).bind(clean(data.name,120),clean(data.client,120),clean(data.objective,1000),clean(data.budget,100),clean(data.status,30)||'planning',clean(data.startDate,30)||null,clean(data.endDate,30)||null,clean(data.notes,3000),Number(data.leadId)||null).run();return true}
export async function updateCampaign(id:number,data:Record<string,unknown>){const db=getOpsDb();if(!db)return false;const allowed=['name','client','objective','budget','status','start_date','end_date','notes'];const map:Record<string,string>={startDate:'start_date',endDate:'end_date'};const sets:string[]=[];const vals:unknown[]=[];for(const [key,val] of Object.entries(data)){const col=map[key]||key;if(allowed.includes(col)&&typeof val==='string'){sets.push(`${col} = ?`);vals.push(clean(val,col==='notes'||col==='objective'?3000:160))}}if(!sets.length)return true;vals.push(id);await db.prepare(`UPDATE shortlists SET ${sets.join(', ')} WHERE id = ?`).bind(...vals).run();return true}

export async function listDeliverables(campaignId?:number){const db=getOpsDb();if(!db)return null;const where=campaignId?'WHERE d.campaign_id = ?':'';const p=db.prepare(`SELECT d.*, c.full_name creator_name FROM deliverables d LEFT JOIN creators c ON c.id=d.creator_id ${where} ORDER BY CASE WHEN d.due_date IS NULL THEN 1 ELSE 0 END, d.due_date ASC, d.id DESC`);const r=campaignId?await p.bind(campaignId).all<DeliverableRecord>():await p.all<DeliverableRecord>();return r.results??[]}
export async function createDeliverable(data:Record<string,unknown>){const db=getOpsDb();if(!db)return false;await db.prepare(`INSERT INTO deliverables (campaign_id,creator_id,title,due_date,status,notes) VALUES (?,?,?,?,?,?)`).bind(Number(data.campaignId),Number(data.creatorId)||null,clean(data.title,180),clean(data.dueDate,30)||null,clean(data.status,30)||'pending',clean(data.notes,2000)).run();return true}
export async function updateDeliverable(id:number,data:Record<string,unknown>){const db=getOpsDb();if(!db)return false;const sets:string[]=[];const vals:unknown[]=[];for(const key of ['title','dueDate','status','notes'])if(typeof data[key]==='string'){const col=key==='dueDate'?'due_date':key;sets.push(`${col} = ?`);vals.push(clean(data[key],key==='notes'?2000:180))}if(!sets.length)return true;sets.push('updated_at = CURRENT_TIMESTAMP');vals.push(id);await db.prepare(`UPDATE deliverables SET ${sets.join(', ')} WHERE id = ?`).bind(...vals).run();return true}

export async function getDashboardStats(){const db=getOpsDb();if(!db)return null;const q=async(sql:string)=>Number((await db.prepare(sql).first<{n:number}>())?.n||0);return {newLeads:await q("SELECT COUNT(*) n FROM leads WHERE status='new'"),approvedCreators:await q("SELECT COUNT(*) n FROM creators WHERE status='approved'"),reviewCreators:await q("SELECT COUNT(*) n FROM creators WHERE status IN ('new','reviewing')"),activeCampaigns:await q("SELECT COUNT(*) n FROM shortlists WHERE status IN ('planning','active')"),dueDeliverables:await q("SELECT COUNT(*) n FROM deliverables WHERE status!='done' AND due_date IS NOT NULL AND date(due_date) <= date('now','+7 day')")}}
