import { getCloudflareContext } from "@opennextjs/cloudflare";

type D1Result<T> = { results?: T[] };
type D1Prepared = { bind:(...values:unknown[])=>D1Prepared; first:<T=unknown>()=>Promise<T|null>; all:<T=unknown>()=>Promise<D1Result<T>>; run:()=>Promise<unknown> };
type D1DatabaseLike = { prepare:(sql:string)=>D1Prepared };
type Env = { VIRA_DB?:D1DatabaseLike };

export type LeadRecord={id:number;created_at:string;updated_at:string;status:string;name:string;company:string;email:string;phone:string|null;service:string|null;budget:string|null;brief:string;notes:string};
export type CampaignRecord={id:number;name:string;created_at:string;client:string;objective:string;creator_brief:string;budget:string;status:string;start_date:string|null;end_date:string|null;notes:string;lead_id:number|null;creator_count:number;deliverable_count:number};
export type DeliverableRecord={id:number;campaign_id:number;creator_id:number|null;title:string;due_date:string|null;status:string;notes:string;instructions:string;submission_url:string|null;submission_note:string;feedback:string;submitted_at:string|null;approved_at:string|null;creator_fee:number;payment_status:string;payment_date:string|null;payment_reference:string;creator_name:string|null};
export type CampaignCreator={id:number;full_name:string;email:string;tiktok:string;city:string;status:string;assignment_status:string};
export type CampaignCreatorStatus='shortlisted'|'invited'|'accepted'|'assigned'|'declined'|'removed';

export function getOpsDb(){try{const {env}=getCloudflareContext();return (env as unknown as Env).VIRA_DB??null}catch{return null}}
const clean=(v:unknown,max=2000)=>typeof v==='string'?v.trim().slice(0,max):'';

export async function saveLead(data:Record<string,unknown>){const db=getOpsDb();if(!db)return {saved:false as const,reason:'DB_NOT_CONFIGURED' as const};await db.prepare(`INSERT INTO leads (name,company,email,phone,service,budget,brief) VALUES (?,?,?,?,?,?,?)`).bind(clean(data.name,80),clean(data.company,120),clean(data.email,160),clean(data.phone,50),clean(data.service,120),clean(data.budget,80),clean(data.message,2000)).run();return {saved:true as const}}

export async function listLeads(){const db=getOpsDb();if(!db)return null;const r=await db.prepare(`SELECT * FROM leads ORDER BY datetime(created_at) DESC LIMIT 250`).all<LeadRecord>();return r.results??[]}
export async function updateLead(id:number,status?:string,notes?:string){const db=getOpsDb();if(!db)return false;const sets:string[]=[];const vals:unknown[]=[];if(status){sets.push('status = ?');vals.push(status)}if(typeof notes==='string'){sets.push('notes = ?');vals.push(notes.slice(0,5000))}if(!sets.length)return true;sets.push('updated_at = CURRENT_TIMESTAMP');vals.push(id);await db.prepare(`UPDATE leads SET ${sets.join(', ')} WHERE id = ?`).bind(...vals).run();return true}

export async function listCampaigns(){const db=getOpsDb();if(!db)return null;const r=await db.prepare(`SELECT c.*, COUNT(DISTINCT CASE WHEN cc.status!='removed' THEN cc.creator_id END) creator_count, COUNT(DISTINCT d.id) deliverable_count FROM campaigns c LEFT JOIN campaign_creators cc ON cc.campaign_id=c.id LEFT JOIN deliverables d ON d.campaign_id=c.id GROUP BY c.id ORDER BY datetime(c.created_at) DESC`).all<CampaignRecord>();return r.results??[]}
export async function createCampaign(data:Record<string,unknown>){const db=getOpsDb();if(!db)return false;await db.prepare(`INSERT INTO campaigns (name,client,objective,creator_brief,budget,status,start_date,end_date,notes,lead_id) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(clean(data.name,120),clean(data.client,120),clean(data.objective,3000),clean(data.creatorBrief,5000),clean(data.budget,100),clean(data.status,30)||'planning',clean(data.startDate,30)||null,clean(data.endDate,30)||null,clean(data.notes,3000),Number(data.leadId)||null).run();return true}
export async function updateCampaign(id:number,data:Record<string,unknown>){const db=getOpsDb();if(!db)return false;const allowed=['name','client','objective','creator_brief','budget','status','start_date','end_date','notes'];const map:Record<string,string>={startDate:'start_date',endDate:'end_date',creatorBrief:'creator_brief'};const sets:string[]=[];const vals:unknown[]=[];for(const [key,val] of Object.entries(data)){const col=map[key]||key;if(allowed.includes(col)&&typeof val==='string'){sets.push(`${col} = ?`);vals.push(clean(val,['notes','objective','creator_brief'].includes(col)?5000:160))}}if(!sets.length)return true;vals.push(id);await db.prepare(`UPDATE campaigns SET ${sets.join(', ')} WHERE id = ?`).bind(...vals).run();return true}

export async function listCampaignCreators(campaignId:number){const db=getOpsDb();if(!db)return null;const r=await db.prepare(`SELECT c.id,c.full_name,c.email,c.tiktok,c.city,c.status,cc.status assignment_status FROM campaign_creators cc JOIN creators c ON c.id=cc.creator_id WHERE cc.campaign_id=? AND cc.status!='removed' ORDER BY CASE cc.status WHEN 'assigned' THEN 0 WHEN 'accepted' THEN 1 WHEN 'invited' THEN 2 WHEN 'shortlisted' THEN 3 ELSE 4 END,c.full_name`).bind(campaignId).all<CampaignCreator>();return r.results??[]}
export async function addCampaignCreator(campaignId:number,creatorId:number,status:CampaignCreatorStatus='assigned'){const db=getOpsDb();if(!db)return false;await db.prepare(`INSERT INTO campaign_creators (campaign_id,creator_id,status,updated_at) VALUES (?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(campaign_id,creator_id) DO UPDATE SET status=excluded.status,updated_at=CURRENT_TIMESTAMP,invited_at=CASE WHEN excluded.status='invited' THEN COALESCE(campaign_creators.invited_at,CURRENT_TIMESTAMP) ELSE campaign_creators.invited_at END,accepted_at=CASE WHEN excluded.status='accepted' THEN COALESCE(campaign_creators.accepted_at,CURRENT_TIMESTAMP) ELSE campaign_creators.accepted_at END`).bind(campaignId,creatorId,status).run();return true}
export async function setCampaignCreatorStatus(campaignId:number,creatorId:number,status:CampaignCreatorStatus){const db=getOpsDb();if(!db)return false;await db.prepare(`UPDATE campaign_creators SET status=?,updated_at=CURRENT_TIMESTAMP,invited_at=CASE WHEN ?='invited' THEN COALESCE(invited_at,CURRENT_TIMESTAMP) ELSE invited_at END,accepted_at=CASE WHEN ?='accepted' THEN COALESCE(accepted_at,CURRENT_TIMESTAMP) ELSE accepted_at END WHERE campaign_id=? AND creator_id=?`).bind(status,status,status,campaignId,creatorId).run();return true}
export async function removeCampaignCreator(campaignId:number,creatorId:number){const db=getOpsDb();if(!db)return false;await db.prepare("UPDATE campaign_creators SET status='removed',updated_at=CURRENT_TIMESTAMP WHERE campaign_id=? AND creator_id=?").bind(campaignId,creatorId).run();await db.prepare("UPDATE deliverables SET creator_id=NULL WHERE campaign_id=? AND creator_id=?").bind(campaignId,creatorId).run();return true}

export async function listDeliverables(campaignId?:number){const db=getOpsDb();if(!db)return null;const where=campaignId?'WHERE d.campaign_id = ?':'';const p=db.prepare(`SELECT d.*, c.full_name creator_name FROM deliverables d LEFT JOIN creators c ON c.id=d.creator_id ${where} ORDER BY CASE WHEN d.due_date IS NULL THEN 1 ELSE 0 END, d.due_date ASC, d.id DESC`);const r=campaignId?await p.bind(campaignId).all<DeliverableRecord>():await p.all<DeliverableRecord>();return r.results??[]}
export async function createDeliverable(data:Record<string,unknown>){const db=getOpsDb();if(!db)return false;const campaignId=Number(data.campaignId),creatorId=Number(data.creatorId)||null;if(creatorId)await addCampaignCreator(campaignId,creatorId,'assigned');await db.prepare(`INSERT INTO deliverables (campaign_id,creator_id,title,due_date,status,notes,instructions,creator_fee,payment_status) VALUES (?,?,?,?,?,?,?,?,?)`).bind(campaignId,creatorId,clean(data.title,180),clean(data.dueDate,30)||null,clean(data.status,30)||'pending',clean(data.notes,2000),clean(data.instructions,4000),Math.max(0,Math.round(Number(data.creatorFee)||0)),clean(data.paymentStatus,30)||'not_set').run();return true}
export async function updateDeliverable(id:number,data:Record<string,unknown>){const db=getOpsDb();if(!db)return false;const map:Record<string,string>={dueDate:'due_date',creatorId:'creator_id',creatorFee:'creator_fee',paymentStatus:'payment_status',paymentDate:'payment_date',paymentReference:'payment_reference',submissionUrl:'submission_url',submissionNote:'submission_note',submittedAt:'submitted_at',approvedAt:'approved_at'};const allowed=new Set(['title','due_date','status','notes','instructions','feedback','creator_id','creator_fee','payment_status','payment_date','payment_reference','submission_url','submission_note','submitted_at','approved_at']);const sets:string[]=[];const vals:unknown[]=[];for(const [key,val] of Object.entries(data)){const col=map[key]||key;if(!allowed.has(col))continue;if(col==='creator_id'){sets.push(`${col} = ?`);vals.push(Number(val)||null);continue}if(col==='creator_fee'){sets.push(`${col} = ?`);vals.push(Math.max(0,Math.round(Number(val)||0)));continue}if(typeof val==='string'){sets.push(`${col} = ?`);vals.push(clean(val,['notes','instructions','feedback','submission_note'].includes(col)?5000:500)||null)}}if(!sets.length)return true;sets.push('updated_at = CURRENT_TIMESTAMP');vals.push(id);await db.prepare(`UPDATE deliverables SET ${sets.join(', ')} WHERE id = ?`).bind(...vals).run();return true}

export async function getDashboardStats(){const db=getOpsDb();if(!db)return null;const q=async(sql:string)=>Number((await db.prepare(sql).first<{n:number}>())?.n||0);return {newLeads:await q("SELECT COUNT(*) n FROM leads WHERE status='new'"),approvedCreators:await q("SELECT COUNT(*) n FROM creators WHERE status='approved'"),reviewCreators:await q("SELECT COUNT(*) n FROM creators WHERE status IN ('new','reviewing')"),activeCampaigns:await q("SELECT COUNT(*) n FROM campaigns WHERE status IN ('planning','active')"),dueDeliverables:await q("SELECT COUNT(*) n FROM deliverables WHERE status NOT IN ('done','approved') AND due_date IS NOT NULL AND date(due_date) <= date('now','+7 day')")}}
