import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/admin-auth";
import { addCampaignCreator,getOpsDb,listCampaignCreators,removeCampaignCreator } from "@/lib/ops-db";
import { sendEmailTo } from "@/lib/email";

export async function GET(request:Request){if(!(await isAdminAuthenticated()))return NextResponse.json({error:'Unauthorized'},{status:401});const id=Number(new URL(request.url).searchParams.get('campaignId')||0);if(!Number.isInteger(id)||id<1)return NextResponse.json({error:'Invalid campaign'},{status:400});const creators=await listCampaignCreators(id);if(!creators)return NextResponse.json({error:'Database unavailable'},{status:503});return NextResponse.json({creators})}

export async function POST(request:Request){if(!(await isAdminAuthenticated()))return NextResponse.json({error:'Unauthorized'},{status:401});const db=getOpsDb();if(!db)return NextResponse.json({error:'Database unavailable'},{status:503});try{const b=await request.json();const campaignId=Number(b.campaignId),creatorId=Number(b.creatorId);if(!Number.isInteger(campaignId)||!Number.isInteger(creatorId))return NextResponse.json({error:'Invalid IDs'},{status:400});if(b.action==='remove'){await removeCampaignCreator(campaignId,creatorId);return NextResponse.json({ok:true})}if(b.action!=='add')return NextResponse.json({error:'Invalid action'},{status:400});const existing=await db.prepare('SELECT 1 ok FROM shortlist_creators WHERE shortlist_id=? AND creator_id=?').bind(campaignId,creatorId).first<{ok:number}>();const creator=await db.prepare("SELECT id,full_name,email,status FROM creators WHERE id=? AND status='approved'").bind(creatorId).first<{id:number;full_name:string;email:string;status:string}>();const campaign=await db.prepare('SELECT id,name,client FROM shortlists WHERE id=?').bind(campaignId).first<{id:number;name:string;client:string}>();if(!creator||!campaign)return NextResponse.json({error:'Approved creator or campaign not found'},{status:404});await addCampaignCreator(campaignId,creatorId);if(!existing){const origin=new URL(request.url).origin;await sendEmailTo(creator.email,`New Vira campaign — ${campaign.name}`,`<div style="font-family:Arial,sans-serif;max-width:600px"><h2>You have been added to a Vira campaign</h2><p>Hi ${creator.full_name}, you have been assigned to <strong>${campaign.name}</strong>${campaign.client?` for ${campaign.client}`:''}.</p><p>Open your creator portal to view the brief and any deliverables assigned to you.</p><p><a href="${origin}/portal/dashboard">Open Creator Portal</a></p></div>`);}
return NextResponse.json({ok:true})}catch{return NextResponse.json({error:'Invalid request'},{status:400})}}
