"use client";
import { FormEvent,useEffect,useState } from "react";
import PortalNav from "./PortalNav";

type Opportunity={id:number;name:string;client:string;application_mode:string;opportunity_summary:string;opportunity_niches:string;opportunity_cities:string;opportunity_platform:string;opportunity_compensation:string;application_deadline:string|null;application_status:string|null;pitch:string|null;proposed_rate:string|null;availability:string|null;applied_at:string|null};
type Data={creator:{full_name:string};opportunities:Opportunity[]};
const parse=(raw:string)=>{try{const v=JSON.parse(raw||'[]');return Array.isArray(v)?v.map(String):[]}catch{return []}};
const label=(v:string)=>v.replaceAll('_',' ');

export default function PortalOpportunities(){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [open,setOpen]=useState<number|null>(null);
 async function load(){const r=await fetch('/api/portal/opportunities',{cache:'no-store'});if(r.status===401){location.href='/portal/login';return}const j=await r.json();if(!r.ok){setError(j.error||'Could not load opportunities');return}setData(j)}
 useEffect(()=>{void load()},[]);
 async function apply(e:FormEvent<HTMLFormElement>,campaignId:number){e.preventDefault();setError('');const fd=new FormData(e.currentTarget);const r=await fetch('/api/portal/opportunities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaignId,pitch:fd.get('pitch'),proposedRate:fd.get('proposedRate'),availability:fd.get('availability')})});const j=await r.json();if(!r.ok){setError(j.error||'Could not submit application');return}setNotice('Application submitted');setOpen(null);setTimeout(()=>setNotice(''),1800);await load()}
 return <main className="portal-shell"><PortalNav/><div className="portal-workspace"><header className="portal-top"><div><span className="portal-kicker">OPPORTUNITIES</span><h1>Campaigns matched to you.</h1><p>Apply to selected Vira campaigns that fit your profile. Applying does not guarantee assignment.</p></div></header>{(error||notice)&&<div className={error?'portal-error':'portal-notice'}>{error||notice}</div>}
 <section className="opportunity-grid">{data?.opportunities.map(o=>{const niches=parse(o.opportunity_niches),cities=parse(o.opportunity_cities);const applied=!!o.application_status;return <article className="opportunity-card" key={o.id}><div className="opportunity-card-head"><div><span className="portal-kicker">{o.client||'Vira campaign'}</span><h2>{o.name}</h2></div>{applied?<b className={`portal-status status-${o.application_status}`}>{label(o.application_status||'')}</b>:<b className="portal-status status-open">Open</b>}</div><p>{o.opportunity_summary||'Vira is inviting creators to express interest in this campaign.'}</p><div className="opportunity-tags">{o.opportunity_platform&&<span>{o.opportunity_platform}</span>}{niches.map(n=><span key={n}>{n}</span>)}{cities.map(c=><span key={c}>{c}</span>)}</div><div className="opportunity-meta"><div><span>Compensation</span><strong>{o.opportunity_compensation||'Shared after selection'}</strong></div><div><span>Apply by</span><strong>{o.application_deadline||'Open until filled'}</strong></div></div>{applied?<div className="opportunity-applied"><strong>Application {label(o.application_status||'')}</strong>{o.proposed_rate&&<span>Proposed rate: {o.proposed_rate}</span>}<span>Vira will contact you if you move forward.</span></div>:open===o.id?<form className="opportunity-form" onSubmit={e=>void apply(e,o.id)}><label>Why are you a good fit?<textarea name="pitch" rows={4} maxLength={1200} placeholder="Share your angle, relevant experience or content idea."/></label><div className="opportunity-form-grid"><label>Proposed rate<input name="proposedRate" maxLength={100} placeholder="e.g. KES 20,000"/></label><label>Availability<input name="availability" maxLength={300} placeholder="e.g. Available next week"/></label></div><div className="opportunity-actions"><button type="button" className="portal-btn secondary" onClick={()=>setOpen(null)}>Cancel</button><button className="portal-btn" type="submit">Submit application</button></div></form>:<button className="portal-btn" onClick={()=>setOpen(o.id)}>View & apply</button>}</article>})}{data&&!data.opportunities.length&&<div className="portal-empty opportunity-empty"><h2>No matching opportunities right now.</h2><p>When Vira opens a campaign that matches your profile, it will appear here.</p></div>}{!data&&!error&&<div className="portal-empty">Loading opportunities…</div>}</section></div></main>
}
