"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { useSearchParams } from "next/navigation";
import AdminNav from "./AdminNav";
type Campaign={id:number;name:string;client:string;objective:string;creator_brief:string;budget:string;status:string;start_date:string|null;end_date:string|null;notes:string;lead_id:number|null;creator_count:number;deliverable_count:number};
type Lead={id:number;company:string;name:string;brief:string;budget:string|null;status:string};
type Creator={id:number;full_name:string;email?:string;status:string;tiktok?:string;city?:string};
type Deliverable={id:number;campaign_id:number;creator_id:number|null;title:string;due_date:string|null;status:string;notes:string;instructions:string;submission_url:string|null;submission_note:string;feedback:string;creator_fee:number;payment_status:string;payment_date:string|null;payment_reference:string;creator_name:string|null};
const campaignStatuses=['planning','active','paused','complete','cancelled'];const deliverableStatuses=['pending','in_progress','submitted','changes_requested','approved','done'];const paymentStatuses=['not_set','pending','paid'];
const money=(n:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0}).format(n||0);
export default function CampaignsAdmin(){const search=useSearchParams();const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [leads,setLeads]=useState<Lead[]>([]);const [creators,setCreators]=useState<Creator[]>([]);const [assigned,setAssigned]=useState<Creator[]>([]);const [deliverables,setDeliverables]=useState<Deliverable[]>([]);const [selected,setSelected]=useState<Campaign|null>(null);const [error,setError]=useState('');const [showCreate,setShowCreate]=useState(Boolean(search.get('lead')));const [feedback,setFeedback]=useState<Record<number,string>>({});const leadId=Number(search.get('lead')||0);
 async function load(){const [cr,lr,rr]=await Promise.all([fetch('/api/admin/campaigns',{cache:'no-store'}),fetch('/api/admin/leads',{cache:'no-store'}),fetch('/api/admin/creators?status=approved',{cache:'no-store'})]);if(cr.status===401){location.href='/admin';return}const cj=await cr.json();if(!cr.ok){setError(cj.error||'Could not load campaigns');return}setCampaigns(cj.campaigns||[]);if(lr.ok){const j=await lr.json();setLeads(j.leads||[])}if(rr.ok){const j=await rr.json();setCreators(j.creators||[])}}
 useEffect(()=>{void load()},[]);useEffect(()=>{if(selected){void loadDeliverables(selected.id);void loadAssigned(selected.id)}},[selected?.id]);
 async function loadDeliverables(id:number){const r=await fetch(`/api/admin/deliverables?campaignId=${id}`,{cache:'no-store'});if(r.ok){const j=await r.json();setDeliverables(j.deliverables||[]);setFeedback(Object.fromEntries((j.deliverables||[]).map((d:Deliverable)=>[d.id,d.feedback||''])))}}
 async function loadAssigned(id:number){const r=await fetch(`/api/admin/campaign-creators?campaignId=${id}`,{cache:'no-store'});if(r.ok){const j=await r.json();setAssigned(j.creators||[])}}
 async function createCampaign(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());const lead=leads.find(l=>l.id===Number(body.leadId));if(lead){body.client=String(body.client||lead.company);body.objective=String(body.objective||lead.brief);body.budget=String(body.budget||lead.budget||'')}const r=await fetch('/api/admin/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error||'Could not create campaign');return}setShowCreate(false);await load();e.currentTarget.reset()}
 async function patchCampaign(id:number,body:Record<string,string>){const r=await fetch('/api/admin/campaigns',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...body})});if(!r.ok)return;await load();setSelected(s=>s&&s.id===id?{...s,...body,creator_brief:body.creatorBrief??s.creator_brief} as Campaign:s)}
 async function assignCreator(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const fd=new FormData(e.currentTarget);const creatorId=Number(fd.get('creatorId'));if(!creatorId)return;const r=await fetch('/api/admin/campaign-creators',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'add',campaignId:selected.id,creatorId})});const j=await r.json();if(!r.ok){setError(j.error||'Could not assign creator');return}await Promise.all([loadAssigned(selected.id),load()]);e.currentTarget.reset()}
 async function removeCreator(creatorId:number){if(!selected)return;await fetch('/api/admin/campaign-creators',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'remove',campaignId:selected.id,creatorId})});await Promise.all([loadAssigned(selected.id),loadDeliverables(selected.id),load()])}
 async function addDeliverable(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());body.campaignId=String(selected.id);const r=await fetch('/api/admin/deliverables',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error||'Could not add deliverable');return}setError('');await Promise.all([loadDeliverables(selected.id),load()]);e.currentTarget.reset()}
 async function patchDeliverable(id:number,patch:Record<string,unknown>){const r=await fetch('/api/admin/deliverables',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...patch})});const j=await r.json();if(!r.ok){setError(j.error||'Could not update deliverable');return}if(selected)await loadDeliverables(selected.id);setError('')}
 const selectedLead=useMemo(()=>leads.find(l=>l.id===leadId),[leads,leadId]);const available=creators.filter(c=>!assigned.some(a=>a.id===c.id));
 return <main className="admin-shell"><AdminNav/><div className="admin-workspace"><header className="admin-top"><div><span className="admin-kicker">CAMPAIGN DELIVERY</span><h1>Campaigns</h1><p>Turn qualified leads into briefs, assign creators, review content and track payments.</p></div><button className="ops-primary ops-button" onClick={()=>setShowCreate(true)}>+ New campaign</button></header>{error&&<p className="admin-error">{error}</p>}<section className="ops-campaign-grid">{campaigns.map(c=><button className="campaign-card" key={c.id} onClick={()=>setSelected(c)}><div className="campaign-card-top"><span>{c.client||'No client'}</span><b className={`status-pill status-${c.status}`}>{c.status}</b></div><h2>{c.name}</h2><p>{c.objective||'No objective added yet.'}</p><div className="campaign-meta"><span>{c.creator_count} creators</span><span>{c.deliverable_count} deliverables</span><span>{c.end_date||'No deadline'}</span></div></button>)}{!campaigns.length&&<div className="admin-empty"><h3>No campaigns yet.</h3><p>Create one from a lead or start a campaign manually.</p></div>}</section></div>
 {showCreate&&<div className="creator-drawer-backdrop" onClick={()=>setShowCreate(false)}><aside className="creator-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setShowCreate(false)}>×</button><span className="admin-kicker">NEW CAMPAIGN</span><h2>Create campaign</h2><form className="ops-form" onSubmit={createCampaign}><label>Lead<select name="leadId" defaultValue={selectedLead?.id||''}><option value="">No linked lead</option>{leads.filter(l=>l.status!=='lost').map(l=><option key={l.id} value={l.id}>{l.company} · {l.name}</option>)}</select></label><label>Campaign name<input name="name" required placeholder="e.g. Back to School Creator Push"/></label><label>Client<input name="client" defaultValue={selectedLead?.company||''}/></label><label>Internal objective<textarea name="objective" defaultValue={selectedLead?.brief||''}/></label><label>Creator brief<textarea name="creatorBrief" placeholder="The brief creators are allowed to see in their portal"/></label><div className="ops-form-grid"><label>Budget<input name="budget" defaultValue={selectedLead?.budget||''}/></label><label>Status<select name="status" defaultValue="planning">{campaignStatuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Start date<input name="startDate" type="date"/></label><label>End date<input name="endDate" type="date"/></label></div><label>Internal notes<textarea name="notes"/></label><button className="ops-primary">Create campaign →</button></form></aside></div>}
 {selected&&<div className="creator-drawer-backdrop" onClick={()=>setSelected(null)}><aside className="creator-drawer campaign-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><span className={`status-pill status-${selected.status}`}>{selected.status}</span><h2>{selected.name}</h2><p className="creator-handle">{selected.client||'No client'} · {selected.budget||'No budget'}</p><div className="drawer-section"><span>STATUS</span><select value={selected.status} onChange={e=>void patchCampaign(selected.id,{status:e.target.value})}>{campaignStatuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="drawer-section"><span>INTERNAL OBJECTIVE</span><p className="drawer-copy">{selected.objective||'No objective yet.'}</p></div><div className="drawer-section"><span>CREATOR BRIEF</span><textarea defaultValue={selected.creator_brief||''} onBlur={e=>void patchCampaign(selected.id,{creatorBrief:e.target.value})} placeholder="This is visible to assigned creators in their portal."/></div>
 <div className="drawer-section"><span>ASSIGNED CREATORS</span><div className="assigned-creators">{assigned.map(c=><div className="assigned-creator" key={c.id}><div><strong>{c.full_name}</strong><small>{c.tiktok||c.email}</small></div><button onClick={()=>void removeCreator(c.id)}>Remove</button></div>)}</div>{available.length>0?<form className="ops-inline-form creator-assign-form" onSubmit={assignCreator}><select name="creatorId" defaultValue=""><option value="">Choose approved creator</option>{available.map(c=><option key={c.id} value={c.id}>{c.full_name}{c.city?` · ${c.city}`:''}</option>)}</select><button className="ops-primary">Assign</button></form>:<p className="ops-muted">All approved creators are already assigned, or no approved creators are available.</p>}</div>
 <div className="drawer-section"><span>DELIVERABLES</span><div className="deliverable-list admin-deliverables">{deliverables.map(d=><div className="deliverable-admin-card" key={d.id}><div className="deliverable-row"><div><strong>{d.title}</strong><span>{d.creator_name||'Unassigned'} · {d.due_date||'No due date'} · {d.creator_fee?money(d.creator_fee):'Fee not set'}</span></div><select value={d.status} onChange={e=>void patchDeliverable(d.id,{status:e.target.value})}>{deliverableStatuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></div>{d.instructions&&<p className="ops-muted">{d.instructions}</p>}{d.submission_url&&<div className="admin-submission"><a href={d.submission_url} target="_blank" rel="noreferrer">Open submitted content ↗</a>{d.submission_note&&<p>{d.submission_note}</p>}</div>}{['submitted','changes_requested'].includes(d.status)&&<div className="review-box"><textarea value={feedback[d.id]??''} onChange={e=>setFeedback({...feedback,[d.id]:e.target.value})} placeholder="Feedback to creator"/><div><button className="ops-secondary" onClick={()=>void patchDeliverable(d.id,{status:'changes_requested',feedback:feedback[d.id]||''})}>Request changes</button><button className="ops-primary" onClick={()=>void patchDeliverable(d.id,{status:'approved',feedback:feedback[d.id]||''})}>Approve</button></div></div>}<div className="payment-box"><span>PAYMENT</span><strong>{d.creator_fee?money(d.creator_fee):'No fee set'}</strong><select value={d.payment_status} onChange={e=>void patchDeliverable(d.id,{paymentStatus:e.target.value})}>{paymentStatuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select><input placeholder="Payment reference" defaultValue={d.payment_reference||''} onBlur={e=>void patchDeliverable(d.id,{paymentReference:e.target.value})}/></div></div>)}</div><form className="ops-form new-deliverable-form" onSubmit={addDeliverable}><input name="title" required placeholder="Deliverable, e.g. TikTok video"/><select name="creatorId" defaultValue=""><option value="">Unassigned</option>{assigned.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select><textarea name="instructions" placeholder="Instructions visible to the creator"/><div className="ops-form-grid"><label>Due date<input name="dueDate" type="date"/></label><label>Creator fee (KES)<input name="creatorFee" type="number" min="0" step="1" placeholder="8000"/></label></div><button className="ops-primary">Add deliverable</button></form></div><div className="drawer-section"><span>INTERNAL NOTES</span><textarea defaultValue={selected.notes||''} onBlur={e=>void patchCampaign(selected.id,{notes:e.target.value})}/></div></aside></div>}</main>}
