"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { useSearchParams } from "next/navigation";
import AdminNav from "./AdminNav";
type Campaign={id:number;name:string;client:string;objective:string;creator_brief:string;budget:string;status:string;start_date:string|null;end_date:string|null;notes:string;lead_id:number|null;creator_count:number;deliverable_count:number};
type Lead={id:number;company:string;name:string;brief:string;budget:string|null;status:string};
const campaignStatuses=['planning','active','paused','complete','cancelled'];
export default function CampaignsAdmin(){const search=useSearchParams();const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [leads,setLeads]=useState<Lead[]>([]);const [error,setError]=useState('');const [showCreate,setShowCreate]=useState(Boolean(search.get('lead')));const leadId=Number(search.get('lead')||0);
 async function load(){const [cr,lr]=await Promise.all([fetch('/api/admin/campaigns',{cache:'no-store'}),fetch('/api/admin/leads',{cache:'no-store'})]);if(cr.status===401){location.href='/admin';return}const cj=await cr.json();if(!cr.ok){setError(cj.error||'Could not load campaigns');return}setCampaigns(cj.campaigns||[]);if(lr.ok){const j=await lr.json();setLeads(j.leads||[])}}
 useEffect(()=>{void load()},[]);
 async function createCampaign(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());const lead=leads.find(l=>l.id===Number(body.leadId));if(lead){body.client=String(body.client||lead.company);body.objective=String(body.objective||lead.brief);body.budget=String(body.budget||lead.budget||'')}const r=await fetch('/api/admin/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error||'Could not create campaign');return}setShowCreate(false);await load();e.currentTarget.reset()}
 const selectedLead=useMemo(()=>leads.find(l=>l.id===leadId),[leads,leadId]);
 return <main className="admin-shell"><AdminNav/><div className="admin-workspace"><header className="admin-top"><div><span className="admin-kicker">CAMPAIGN DELIVERY</span><h1>Campaigns</h1><p>Turn qualified leads into briefs, assign creators, review content and track payments.</p></div><button className="ops-primary ops-button" onClick={()=>setShowCreate(true)}>+ New campaign</button></header>{error&&<p className="admin-error">{error}</p>}<section className="ops-campaign-grid">{campaigns.map(c=><a className="campaign-card" key={c.id} href={`/admin/campaigns/${c.id}`}><div className="campaign-card-top"><span>{c.client||'No client'}</span><b className={`status-pill status-${c.status}`}>{c.status}</b></div><h2>{c.name}</h2><p>{c.objective||'No objective added yet.'}</p><div className="campaign-meta"><span>{c.creator_count} creators</span><span>{c.deliverable_count} deliverables</span><span>{c.end_date||'No deadline'}</span></div></a>)}{!campaigns.length&&<div className="admin-empty"><h3>No campaigns yet.</h3><p>Create one from a lead or start a campaign manually.</p></div>}</section></div>
 {showCreate&&<div className="creator-drawer-backdrop" onClick={()=>setShowCreate(false)}><aside className="creator-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setShowCreate(false)}>×</button><span className="admin-kicker">NEW CAMPAIGN</span><h2>Create campaign</h2><form className="ops-form" onSubmit={createCampaign}><label>Lead<select name="leadId" defaultValue={selectedLead?.id||''}><option value="">No linked lead</option>{leads.filter(l=>l.status!=='lost').map(l=><option key={l.id} value={l.id}>{l.company} · {l.name}</option>)}</select></label><label>Campaign name<input name="name" required placeholder="e.g. Back to School Creator Push"/></label><label>Client<input name="client" defaultValue={selectedLead?.company||''}/></label><label>Internal objective<textarea name="objective" defaultValue={selectedLead?.brief||''}/></label><label>Creator brief<textarea name="creatorBrief" placeholder="The brief creators are allowed to see in their portal"/></label><div className="ops-form-grid"><label>Budget<input name="budget" defaultValue={selectedLead?.budget||''}/></label><label>Status<select name="status" defaultValue="planning">{campaignStatuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Start date<input name="startDate" type="date"/></label><label>End date<input name="endDate" type="date"/></label></div><label>Internal notes<textarea name="notes"/></label><button className="ops-primary">Create campaign →</button></form></aside></div>}</main>}
