"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import AdminNav from "./AdminNav";
import FinancePanel from "./FinancePanel";

type Campaign={id:number;name:string;created_at:string;client:string;objective:string;creator_brief:string;budget:string;status:string;start_date:string|null;end_date:string|null;notes:string;lead_id:number|null;creator_count:number;deliverable_count:number};
type CreatorAssignmentStatus="shortlisted"|"invited"|"accepted"|"assigned"|"declined"|"removed";
type Creator={id:number;full_name:string;email:string;tiktok:string;city:string;status:string;assignment_status?:CreatorAssignmentStatus};
type Client={id:number;company:string;contact_name:string;email:string;phone:string;status:string;campaign_count?:number};
type Deliverable={id:number;campaign_id:number;creator_id:number|null;title:string;due_date:string|null;status:string;notes:string;instructions:string;submission_url:string|null;submission_note:string;feedback:string;submitted_at:string|null;approved_at:string|null;creator_fee:number;payment_status:string;payment_date:string|null;payment_reference:string;creator_name:string|null;client_approval_status?:string;client_feedback?:string;client_reviewed_at?:string|null;internal_review_version_id?:number|null;client_submission_version_id?:number|null};
type ReportDeliverable=Deliverable&{views?:number;reach?:number;impressions?:number;likes?:number;comments?:number;shares?:number;saves?:number;clicks?:number;conversions?:number;spend?:number};
type ReportCampaign={client_objective?:string;report_summary?:string;report_insights?:string;report_recommendations?:string};
type ActivityEvent={id:number;created_at:string;actor_type:string;event_type:string;title:string;detail:string;metadata?:Record<string,unknown>};
type SubmissionVersion={id:number;deliverable_id:number;version_number:number;creator_id:number;source_type:"r2"|"external";r2_key:string|null;external_url:string|null;file_name:string|null;mime_type:string|null;file_size:number|null;creator_note:string;created_at:string;internal_review_version_id?:number|null;client_submission_version_id?:number|null};
type ReviewEvent={id:number;deliverable_id:number;submission_version_id:number;reviewer_type:"admin"|"client";reviewer_id:number|null;action:"approved"|"changes_requested"|"shared_with_client";feedback:string;created_at:string};
type Tab="overview"|"creators"|"deliverables"|"review"|"performance"|"finance"|"report"|"activity";

const campaignStatuses=["planning","active","paused","complete","cancelled"];
const creatorAssignmentStatuses:CreatorAssignmentStatus[]=["shortlisted","invited","accepted","assigned","declined"];
const deliverableStatuses=["pending","in_progress","submitted","changes_requested","approved","done"];
const paymentStatuses=["not_set","pending","paid"];
const tabs:[Tab,string][]=[["overview","Overview"],["creators","Creators"],["deliverables","Deliverables"],["review","Review"],["performance","Performance"],["finance","Finance"],["report","Report"],["activity","Activity"]];
const money=(n:number)=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(n||0);
const integer=(n:number)=>new Intl.NumberFormat("en-KE",{maximumFractionDigits:0}).format(n||0);
const label=(v:string)=>v.replaceAll("_"," ");
const versionUrl=(v:SubmissionVersion)=>v.source_type==="r2"?`/api/media/submissions/${v.id}`:v.external_url||"#";

export default function CampaignWorkspace({campaignId}:{campaignId:number}){
 const [campaign,setCampaign]=useState<Campaign|null>(null);
 const [creators,setCreators]=useState<Creator[]>([]);
 const [campaignCreators,setCampaignCreators]=useState<Creator[]>([]);
 const [clients,setClients]=useState<Client[]>([]);
 const [linkedClients,setLinkedClients]=useState<Client[]>([]);
 const [deliverables,setDeliverables]=useState<Deliverable[]>([]);
 const [reportDeliverables,setReportDeliverables]=useState<ReportDeliverable[]>([]);
 const [reportCampaign,setReportCampaign]=useState<ReportCampaign>({});
 const [activityEvents,setActivityEvents]=useState<ActivityEvent[]>([]);
 const [reviewVersions,setReviewVersions]=useState<SubmissionVersion[]>([]);
 const [reviewEvents,setReviewEvents]=useState<ReviewEvent[]>([]);
 const [tab,setTab]=useState<Tab>("overview");
 const [feedback,setFeedback]=useState<Record<number,string>>({});
 const [error,setError]=useState("");
 const [notice,setNotice]=useState("");
 const [loading,setLoading]=useState(true);

 async function load(){
  setLoading(true);setError("");
  const [campaignRes,creatorRes,assignedRes,clientRes,linkedRes,deliverableRes,reportRes,activityRes,reviewsRes]=await Promise.all([
   fetch("/api/admin/campaigns",{cache:"no-store"}),
   fetch("/api/admin/creators?status=approved",{cache:"no-store"}),
   fetch(`/api/admin/campaign-creators?campaignId=${campaignId}`,{cache:"no-store"}),
   fetch("/api/admin/clients",{cache:"no-store"}),
   fetch(`/api/admin/clients?campaignId=${campaignId}`,{cache:"no-store"}),
   fetch(`/api/admin/deliverables?campaignId=${campaignId}`,{cache:"no-store"}),
   fetch(`/api/admin/reporting?campaignId=${campaignId}`,{cache:"no-store"}),
   fetch(`/api/admin/activity?campaignId=${campaignId}`,{cache:"no-store"}),
   fetch(`/api/admin/reviews?campaignId=${campaignId}`,{cache:"no-store"})
  ]);
  if(campaignRes.status===401){location.href="/admin";return}
  const cj=await campaignRes.json();
  if(!campaignRes.ok){setError(cj.error||"Could not load campaign");setLoading(false);return}
  const found=(cj.campaigns||[]).find((c:Campaign)=>c.id===campaignId)||null;
  setCampaign(found);
  if(creatorRes.ok){const j=await creatorRes.json();setCreators(j.creators||[])}
  if(assignedRes.ok){const j=await assignedRes.json();setCampaignCreators(j.creators||[])}
  if(clientRes.ok){const j=await clientRes.json();setClients(j.clients||[])}
  if(linkedRes.ok){const j=await linkedRes.json();setLinkedClients(j.clients||[])}
  if(deliverableRes.ok){const j=await deliverableRes.json();const items=j.deliverables||[];setDeliverables(items);setFeedback(Object.fromEntries(items.map((d:Deliverable)=>[d.id,d.feedback||""])))}
  if(reportRes.ok){const j=await reportRes.json();setReportCampaign(j.campaign||{});setReportDeliverables(j.deliverables||[])}
  if(activityRes.ok){const j=await activityRes.json();setActivityEvents(j.events||[])}
  if(reviewsRes.ok){const j=await reviewsRes.json();setReviewVersions(j.versions||[]);setReviewEvents(j.events||[])}
  setLoading(false);
 }
 useEffect(()=>{void load()},[campaignId]);

 async function patchCampaign(patch:Record<string,string>){if(!campaign)return;const r=await fetch("/api/admin/campaigns",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:campaign.id,...patch})});const j=await r.json();if(!r.ok){setError(j.error||"Could not update campaign");return}setCampaign(c=>c?{...c,...patch,creator_brief:patch.creatorBrief??c.creator_brief,start_date:patch.startDate??c.start_date,end_date:patch.endDate??c.end_date}:c);setNotice("Campaign updated");setTimeout(()=>setNotice(""),1800);await load()}
 async function assignCreator(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const creatorId=Number(fd.get("creatorId"));if(!creatorId)return;const r=await fetch("/api/admin/campaign-creators",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"add",campaignId,creatorId,status:"assigned"})});const j=await r.json();if(!r.ok){setError(j.error||"Could not assign creator");return}e.currentTarget.reset();await load()}
 async function updateCreatorStatus(creatorId:number,status:CreatorAssignmentStatus){const r=await fetch("/api/admin/campaign-creators",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"add",campaignId,creatorId,status})});const j=await r.json();if(!r.ok){setError(j.error||"Could not update creator status");return}await load()}
 async function removeCreator(creatorId:number){const r=await fetch("/api/admin/campaign-creators",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"remove",campaignId,creatorId})});if(!r.ok){const j=await r.json().catch(()=>({}));setError(j.error||"Could not remove creator");return}await load()}
 async function addDeliverable(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());body.campaignId=String(campaignId);const r=await fetch("/api/admin/deliverables",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error||"Could not add deliverable");return}e.currentTarget.reset();await load()}
 async function patchDeliverable(id:number,patch:Record<string,unknown>){const r=await fetch("/api/admin/deliverables",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...patch})});const j=await r.json();if(!r.ok){setError(j.error||"Could not update deliverable");return}await load()}
 async function reviewVersion(deliverableId:number,versionId:number,action:"approved"|"changes_requested"){const r=await fetch("/api/admin/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deliverableId,versionId,action,feedback:feedback[deliverableId]||""})});const j=await r.json();if(!r.ok){setError(j.error||"Could not save review");return}setFeedback(f=>({...f,[deliverableId]:""}));setNotice(action==="approved"?`V${j.versionNumber} approved`:`Revision requested on V${j.versionNumber}`);setTimeout(()=>setNotice(""),1800);await load()}
 async function linkClient(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const clientId=Number(fd.get("clientId"));if(!clientId)return;const r=await fetch("/api/admin/clients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"link",campaignId,clientId})});const j=await r.json();if(!r.ok){setError(j.error||"Could not link client");return}e.currentTarget.reset();await load()}
 async function unlinkClient(clientId:number){await fetch("/api/admin/clients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"unlink",campaignId,clientId})});await load()}
 async function shareForClient(deliverableId:number,status:string){const r=await fetch("/api/admin/reporting",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"share",campaignId,deliverableId,clientApprovalStatus:status})});const j=await r.json();if(!r.ok){setError(j.error||"Could not update client review");return}await load()}
 async function saveMetrics(d:ReportDeliverable,form:HTMLFormElement){const fd=new FormData(form);const body=Object.fromEntries(fd.entries());const r=await fetch("/api/admin/reporting",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"metrics",campaignId,deliverableId:d.id,...body})});const j=await r.json();if(!r.ok){setError(j.error||"Could not save metrics");return}setNotice("Metrics saved");setTimeout(()=>setNotice(""),1800);await load()}
 async function saveReport(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/admin/reporting",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"campaign",campaignId,...body})});const j=await r.json();if(!r.ok){setError(j.error||"Could not save report");return}setNotice("Report saved");setTimeout(()=>setNotice(""),1800);await load()}

 const assignedCreators=campaignCreators.filter(c=>c.assignment_status==="assigned");
 const availableCreators=creators.filter(c=>!campaignCreators.some(a=>a.id===c.id));
 const availableClients=clients.filter(c=>!linkedClients.some(l=>l.id===c.id)&&c.status==="active");
 const totals=useMemo(()=>reportDeliverables.reduce((a,d)=>({views:a.views+Number(d.views||0),reach:a.reach+Number(d.reach||0),likes:a.likes+Number(d.likes||0),comments:a.comments+Number(d.comments||0),shares:a.shares+Number(d.shares||0),clicks:a.clicks+Number(d.clicks||0),conversions:a.conversions+Number(d.conversions||0),spend:a.spend+Number(d.spend||0)}),{views:0,reach:0,likes:0,comments:0,shares:0,clicks:0,conversions:0,spend:0}),[reportDeliverables]);
 const finance=useMemo(()=>deliverables.reduce((a,d)=>({committed:a.committed+Number(d.creator_fee||0),paid:a.paid+(d.payment_status==="paid"?Number(d.creator_fee||0):0),outstanding:a.outstanding+(d.payment_status!=="paid"?Number(d.creator_fee||0):0)}),{committed:0,paid:0,outstanding:0}),[deliverables]);
 const progress=deliverables.length?Math.round(deliverables.filter(d=>["approved","done"].includes(d.status)).length/deliverables.length*100):0;

 if(loading)return <main className="admin-shell"><AdminNav/><div className="admin-centre"><div className="admin-loader">Loading campaign workspace...</div></div></main>;
 if(!campaign)return <main className="admin-shell"><AdminNav/><div className="admin-workspace"><div className="admin-empty"><h2>Campaign not found.</h2><a href="/admin/campaigns">← Back to campaigns</a></div></div></main>;
 return <main className="admin-shell"><AdminNav/><div className="admin-workspace campaign-workspace">
  <header className="workspace-hero"><div><a className="workspace-back" href="/admin/campaigns">← Campaigns</a><div className="workspace-title-row"><div><span className="admin-kicker">CAMPAIGN WORKSPACE</span><h1>{campaign.name}</h1><p>{campaign.client||"No client set"} · {campaign.start_date||"No start date"} → {campaign.end_date||"No end date"}</p></div><select className={`workspace-status status-${campaign.status}`} value={campaign.status} onChange={e=>void patchCampaign({status:e.target.value})}>{campaignStatuses.map(s=><option key={s}>{s}</option>)}</select></div></div></header>
  {(error||notice)&&<div className={error?"admin-error":"workspace-notice"}>{error||notice}</div>}
  <nav className="workspace-tabs">{tabs.map(([id,text])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{text}</button>)}</nav>

  {tab==="overview"&&<div className="workspace-grid overview-grid">
   <section className="workspace-panel workspace-span-2"><div className="panel-head"><div><span>CAMPAIGN HEALTH</span><h2>{progress}% complete</h2></div><strong>{deliverables.filter(d=>["approved","done"].includes(d.status)).length}/{deliverables.length} deliverables</strong></div><div className="progress-track"><i style={{width:`${progress}%`}}/></div><div className="workspace-kpis"><div><span>Assigned creators</span><strong>{assignedCreators.length}</strong></div><div><span>Awaiting review</span><strong>{deliverables.filter(d=>d.status==="submitted").length}</strong></div><div><span>Client review</span><strong>{reportDeliverables.filter(d=>d.client_approval_status==="awaiting_client").length}</strong></div><div><span>Outstanding fees</span><strong>{money(finance.outstanding)}</strong></div></div></section>
   <section className="workspace-panel"><div className="panel-head"><div><span>CLIENT ACCESS</span><h2>Linked clients</h2></div></div>{linkedClients.map(c=><div className="workspace-person" key={c.id}><div><strong>{c.company}</strong><span>{c.contact_name} · {c.email}</span></div><button onClick={()=>void unlinkClient(c.id)}>Remove</button></div>)}{!linkedClients.length&&<p className="ops-muted">No client portal access linked yet.</p>}{availableClients.length>0&&<form className="ops-inline-form" onSubmit={linkClient}><select name="clientId" defaultValue=""><option value="">Link client account</option>{availableClients.map(c=><option key={c.id} value={c.id}>{c.company} · {c.contact_name}</option>)}</select><button className="ops-primary">Link</button></form>}</section>
   <section className="workspace-panel"><div className="panel-head"><div><span>CAMPAIGN DETAILS</span><h2>Brief</h2></div></div><label className="workspace-field">Internal objective<textarea defaultValue={campaign.objective||""} onBlur={e=>void patchCampaign({objective:e.target.value})}/></label><label className="workspace-field">Creator brief<textarea defaultValue={campaign.creator_brief||""} onBlur={e=>void patchCampaign({creatorBrief:e.target.value})}/></label><div className="workspace-field-grid"><label className="workspace-field">Budget<input defaultValue={campaign.budget||""} onBlur={e=>void patchCampaign({budget:e.target.value})}/></label><label className="workspace-field">Start<input type="date" defaultValue={campaign.start_date||""} onBlur={e=>void patchCampaign({startDate:e.target.value})}/></label><label className="workspace-field">End<input type="date" defaultValue={campaign.end_date||""} onBlur={e=>void patchCampaign({endDate:e.target.value})}/></label></div></section>
   <section className="workspace-panel workspace-span-2"><div className="panel-head"><div><span>OPERATIONS</span><h2>What needs attention</h2></div></div><div className="attention-list"><button onClick={()=>setTab("review")}><strong>{deliverables.filter(d=>d.status==="submitted").length}</strong><span>creator submissions waiting for internal review</span></button><button onClick={()=>setTab("review")}><strong>{reportDeliverables.filter(d=>d.client_approval_status==="awaiting_client").length}</strong><span>items currently with the client</span></button><button onClick={()=>setTab("finance")}><strong>{deliverables.filter(d=>d.creator_fee>0&&d.payment_status!=="paid").length}</strong><span>creator payments still outstanding</span></button></div></section>
  </div>}

  {tab==="creators"&&<section className="workspace-panel"><div className="panel-head"><div><span>CREATOR ROSTER</span><h2>{campaignCreators.length} in pipeline · {assignedCreators.length} assigned</h2></div></div><div className="creator-roster">{campaignCreators.map(c=><article key={c.id}><div className="creator-avatar">{c.full_name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><strong>{c.full_name}</strong><span>{c.city||"Location not set"} · {c.tiktok||c.email}</span></div><select value={c.assignment_status||"assigned"} onChange={e=>void updateCreatorStatus(c.id,e.target.value as CreatorAssignmentStatus)}>{creatorAssignmentStatuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><button onClick={()=>void removeCreator(c.id)}>Remove</button></article>)}</div>{!campaignCreators.length&&<p className="ops-muted">No creators in this campaign yet.</p>}{availableCreators.length>0&&<form className="assign-bar" onSubmit={assignCreator}><div><span>ASSIGN CREATOR</span><select name="creatorId" defaultValue=""><option value="">Choose approved creator</option>{availableCreators.map(c=><option key={c.id} value={c.id}>{c.full_name}{c.city?` · ${c.city}`:""}</option>)}</select></div><button className="ops-primary">Assign creator</button></form>}</section>}

  {tab==="deliverables"&&<div className="workspace-grid deliverables-grid"><section className="workspace-panel workspace-span-2"><div className="panel-head"><div><span>DELIVERY BOARD</span><h2>{deliverables.length} deliverables</h2></div></div><div className="workspace-deliverables">{deliverables.map(d=><article key={d.id}><div className="deliverable-head"><div><strong>{d.title}</strong><span>{d.creator_name||"Unassigned"} · Due {d.due_date||"not set"}</span></div><select value={d.status} onChange={e=>void patchDeliverable(d.id,{status:e.target.value})}>{deliverableStatuses.map(s=><option key={s} value={s} disabled={["changes_requested","approved"].includes(s)}>{label(s)}</option>)}</select></div>{d.instructions&&<p>{d.instructions}</p>}{d.submission_url&&<a href={d.submission_url} target="_blank" rel="noreferrer">Open latest submission ↗</a>}</article>)}{!deliverables.length&&<p className="ops-muted">No deliverables yet.</p>}</div></section><section className="workspace-panel"><div className="panel-head"><div><span>NEW DELIVERABLE</span><h2>Add work item</h2></div></div><form className="ops-form" onSubmit={addDeliverable}><label>Title<input name="title" required placeholder="e.g. TikTok video"/></label><label>Creator<select name="creatorId" defaultValue=""><option value="">Unassigned</option>{assignedCreators.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><label>Instructions<textarea name="instructions" placeholder="What the creator needs to produce"/></label><label>Due date<input type="date" name="dueDate"/></label><label>Creator fee (KES)<input type="number" min="0" step="1" name="creatorFee"/></label><button className="ops-primary">Add deliverable</button></form></section></div>}

  {tab==="review"&&<section className="workspace-panel"><div className="panel-head"><div><span>VERSION REVIEW</span><h2>Internal → client approval</h2></div></div><div className="review-list">{deliverables.map(d=>{const report=reportDeliverables.find(r=>r.id===d.id);const versions=reviewVersions.filter(v=>v.deliverable_id===d.id).sort((a,b)=>b.version_number-a.version_number);const latest=versions[0];const events=reviewEvents.filter(e=>e.deliverable_id===d.id);return <article key={d.id}><div className="deliverable-head"><div><strong>{d.title}</strong><span>{d.creator_name||"Unassigned"} · Internal: {label(d.status)} · Client: {label(report?.client_approval_status||"not_ready")}</span></div>{latest&&<a href={versionUrl(latest)} target="_blank" rel="noreferrer">Open V{latest.version_number} ↗</a>}</div>{versions.length>0?<div className="portal-version-list">{versions.map(v=>{const versionEvents=events.filter(e=>e.submission_version_id===v.id);return <div className="portal-version" key={v.id}><div><strong>V{v.version_number}</strong><span>{v.file_name||v.source_type} · {new Date(v.created_at).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"})}</span>{v.creator_note&&<p>{v.creator_note}</p>}{versionEvents.map(e=><small key={e.id}>{label(e.reviewer_type)} · {label(e.action)}{e.feedback?` · ${e.feedback}`:""}</small>)}</div><a href={versionUrl(v)} target="_blank" rel="noreferrer">View ↗</a></div>})}</div>:<p className="ops-muted">No submission versions yet.</p>}{latest&&d.status==="submitted"&&<div className="review-actions"><textarea value={feedback[d.id]??""} onChange={e=>setFeedback({...feedback,[d.id]:e.target.value})} placeholder={`Feedback for V${latest.version_number}`}/><div><button className="ops-secondary" onClick={()=>void reviewVersion(d.id,latest.id,"changes_requested")}>Request V{latest.version_number} changes</button><button className="ops-primary" onClick={()=>void reviewVersion(d.id,latest.id,"approved")}>Approve V{latest.version_number}</button></div></div>}{d.status==="changes_requested"&&<p className="client-feedback"><strong>Waiting for revision.</strong> {d.feedback||"The creator has been asked to submit a new version."}</p>}{["approved","done"].includes(d.status)&&<div className="client-review-bar"><span>{report?.client_approval_status==="awaiting_client"?`V${latest?.version_number||""} is with the client`:report?.client_approval_status==="approved"?"Client approved":report?.client_approval_status==="changes_requested"?"Client requested changes":"Internally approved version is ready for client review"}</span>{report?.client_approval_status!=="approved"&&<button className="ops-primary" onClick={()=>void shareForClient(d.id,"awaiting_client")}>Share approved version</button>}</div>}{report?.client_feedback&&<p className="client-feedback"><strong>Client feedback:</strong> {report.client_feedback}</p>}</article>})}</div></section>}

  {tab==="performance"&&<><section className="workspace-kpis performance-kpis"><div><span>Total views</span><strong>{integer(totals.views)}</strong></div><div><span>Reach</span><strong>{integer(totals.reach)}</strong></div><div><span>Engagements</span><strong>{integer(totals.likes+totals.comments+totals.shares)}</strong></div><div><span>Conversions</span><strong>{integer(totals.conversions)}</strong></div><div><span>Media spend</span><strong>{money(totals.spend)}</strong></div></section><section className="workspace-panel"><div className="panel-head"><div><span>PERFORMANCE INPUT</span><h2>Deliverable metrics</h2></div></div><div className="metrics-list">{reportDeliverables.map(d=><form key={d.id} onSubmit={e=>{e.preventDefault();void saveMetrics(d,e.currentTarget)}}><div><strong>{d.title}</strong><span>{d.creator_name||"Unassigned"}</span></div>{[["views","Views"],["reach","Reach"],["likes","Likes"],["comments","Comments"],["shares","Shares"],["clicks","Clicks"],["conversions","Conversions"],["spend","Spend"]].map(([key,text])=><label key={key}>{text}<input name={key} type="number" min="0" step={key==="spend"?"0.01":"1"} defaultValue={String((d as unknown as Record<string,unknown>)[key]||0)}/></label>)}<button className="ops-primary">Save</button></form>)}</div></section></>}

  {tab==="finance"&&<><FinancePanel campaignId={campaignId}/><section className="workspace-panel"><div className="panel-head"><div><span>CREATOR PAYOUTS</span><h2>Payment tracker</h2></div></div><div className="finance-list">{deliverables.map(d=><article key={d.id}><div><strong>{d.creator_name||"Unassigned creator"}</strong><span>{d.title}</span></div><strong>{money(d.creator_fee)}</strong><select value={d.payment_status} onChange={e=>void patchDeliverable(d.id,{paymentStatus:e.target.value})}>{paymentStatuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><input placeholder="Payment reference" defaultValue={d.payment_reference||""} onBlur={e=>void patchDeliverable(d.id,{paymentReference:e.target.value})}/></article>)}</div></section></>}

  {tab==="report"&&<section className="workspace-panel report-panel"><div className="panel-head"><div><span>CLIENT REPORT</span><h2>Campaign narrative</h2></div></div><form className="report-form" onSubmit={saveReport}><label>Client objective<textarea name="clientObjective" defaultValue={reportCampaign.client_objective||""}/></label><label>Executive summary<textarea name="reportSummary" defaultValue={reportCampaign.report_summary||""}/></label><label>Key insights<textarea name="reportInsights" defaultValue={reportCampaign.report_insights||""}/></label><label>Recommendations<textarea name="reportRecommendations" defaultValue={reportCampaign.report_recommendations||""}/></label><button className="ops-primary">Save report narrative</button></form></section>}

  {tab==="activity"&&<section className="workspace-panel"><div className="panel-head"><div><span>TIMELINE</span><h2>Campaign activity</h2></div></div><div className="activity-list">{activityEvents.map(a=><article key={a.id}><time>{new Date(a.created_at).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"})}</time><div><strong>{a.title}</strong><span>{a.detail||label(a.event_type)}</span><small>{label(a.actor_type)}</small></div></article>)}{!activityEvents.length&&<p className="ops-muted">No recorded activity yet.</p>}</div></section>}
 </div></main>
}
