"use client";

import { FormEvent,useCallback,useEffect,useState } from "react";

type Totals={commercialValue:number;invoicedAmount:number;clientPaid:number;clientOutstanding:number;creatorCommitted:number;creatorPaid:number;creatorOutstanding:number;productionCosts:number;manualMediaCosts:number;boostedSpend:number;otherCosts:number;totalCosts:number;grossMargin:number};
type Cost={id:number;category:string;amount:number;vendor:string;notes:string;incurred_at:string};
type Payment={id:number;amount:number;paid_at:string;reference:string;notes:string;client_company:string|null};
type FinanceData={campaign:{commercialValue:number;invoicedAmount:number};totals:Totals;costs:Cost[];payments:Payment[]};
const money=(n:number)=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(n||0);
const label=(s:string)=>s.replaceAll("_"," ");

export default function FinancePanel({campaignId}:{campaignId:number}){
 const [data,setData]=useState<FinanceData|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const r=await fetch(`/api/admin/finance?campaignId=${campaignId}`,{cache:"no-store"});const j=await r.json();if(!r.ok){setError(j.error||"Could not load finance");setLoading(false);return}setData(j);setError("");setLoading(false)},[campaignId]);
 useEffect(()=>{void load()},[load]);
 async function saveCommercial(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/admin/finance",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaignId,...body})});const j=await r.json();if(!r.ok){setError(j.error||"Could not save commercial terms");return}setNotice("Commercial terms saved");setTimeout(()=>setNotice(""),1800);await load()}
 async function add(e:FormEvent<HTMLFormElement>,kind:"cost"|"payment"){e.preventDefault();const form=e.currentTarget;const body=Object.fromEntries(new FormData(form).entries());const r=await fetch("/api/admin/finance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaignId,kind,...body})});const j=await r.json();if(!r.ok){setError(j.error||`Could not add ${kind}`);return}form.reset();setNotice(kind==="cost"?"Cost recorded":"Client payment recorded");setTimeout(()=>setNotice(""),1800);await load()}
 async function remove(kind:"cost"|"payment",id:number){const r=await fetch("/api/admin/finance",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,id})});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||"Could not remove record");return}await load()}
 if(loading)return <section className="workspace-panel"><p className="ops-muted">Loading finance…</p></section>;
 if(!data)return <section className="workspace-panel"><p className="admin-error">{error||"Finance unavailable"}</p></section>;
 const t=data.totals;
 return <div className="finance-lite">
  {(error||notice)&&<div className={error?"admin-error":"workspace-notice"}>{error||notice}</div>}
  <section className="workspace-kpis performance-kpis"><div><span>Campaign value</span><strong>{money(t.commercialValue)}</strong></div><div><span>Client invoiced</span><strong>{money(t.invoicedAmount)}</strong></div><div><span>Client paid</span><strong>{money(t.clientPaid)}</strong></div><div><span>Client outstanding</span><strong>{money(t.clientOutstanding)}</strong></div><div><span>Total costs</span><strong>{money(t.totalCosts)}</strong></div><div><span>Gross margin</span><strong>{money(t.grossMargin)}</strong></div></section>
  <div className="workspace-grid deliverables-grid">
   <section className="workspace-panel"><div className="panel-head"><div><span>COMMERCIAL</span><h2>Campaign value</h2></div></div><form className="ops-form" onSubmit={saveCommercial}><label>Contracted value (KES)<input name="commercialValue" type="number" min="0" step="0.01" defaultValue={String(data.campaign.commercialValue||0)}/></label><label>Client invoiced (KES)<input name="invoicedAmount" type="number" min="0" step="0.01" defaultValue={String(data.campaign.invoicedAmount||0)}/></label><button className="ops-primary">Save commercial terms</button></form></section>
   <section className="workspace-panel"><div className="panel-head"><div><span>COST BREAKDOWN</span><h2>Margin inputs</h2></div></div><div className="finance-list"><article><div><strong>Creator commitments</strong><span>{money(t.creatorPaid)} paid · {money(t.creatorOutstanding)} outstanding</span></div><strong>{money(t.creatorCommitted)}</strong></article><article><div><strong>Production</strong><span>Manual campaign costs</span></div><strong>{money(t.productionCosts)}</strong></article><article><div><strong>Media</strong><span>{money(t.manualMediaCosts)} manual · {money(t.boostedSpend)} boosted posts</span></div><strong>{money(t.manualMediaCosts+t.boostedSpend)}</strong></article><article><div><strong>Other</strong><span>Other campaign costs</span></div><strong>{money(t.otherCosts)}</strong></article></div></section>
   <section className="workspace-panel"><div className="panel-head"><div><span>ADD COST</span><h2>Campaign expense</h2></div></div><form className="ops-form" onSubmit={e=>void add(e,"cost")}><label>Category<select name="category" defaultValue="production"><option value="production">Production</option><option value="media">Media</option><option value="other">Other</option></select></label><label>Amount (KES)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Vendor / payee<input name="vendor" placeholder="Optional"/></label><label>Incurred date<input name="incurredAt" type="date"/></label><label>Notes<textarea name="notes" placeholder="Optional"/></label><button className="ops-primary">Record cost</button></form></section>
   <section className="workspace-panel"><div className="panel-head"><div><span>CLIENT RECEIPT</span><h2>Record payment</h2></div></div><form className="ops-form" onSubmit={e=>void add(e,"payment")}><label>Amount received (KES)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Paid date<input name="paidAt" type="date"/></label><label>Reference<input name="reference" placeholder="Receipt, bank or M-Pesa reference"/></label><label>Notes<textarea name="notes" placeholder="Optional"/></label><button className="ops-primary">Record client payment</button></form></section>
   <section className="workspace-panel workspace-span-2"><div className="panel-head"><div><span>COST LEDGER</span><h2>{data.costs.length} campaign costs</h2></div></div><div className="finance-list">{data.costs.map(c=><article key={c.id}><div><strong>{label(c.category)} · {c.vendor||"No vendor"}</strong><span>{c.incurred_at}{c.notes?` · ${c.notes}`:""}</span></div><strong>{money(c.amount)}</strong><button onClick={()=>void remove("cost",c.id)}>Remove</button></article>)}{!data.costs.length&&<p className="ops-muted">No non-creator campaign costs recorded.</p>}</div></section>
   <section className="workspace-panel workspace-span-2"><div className="panel-head"><div><span>CLIENT PAYMENTS</span><h2>{data.payments.length} receipts</h2></div></div><div className="finance-list">{data.payments.map(p=><article key={p.id}><div><strong>{p.client_company||"Campaign client"}</strong><span>{p.paid_at}{p.reference?` · ${p.reference}`:""}{p.notes?` · ${p.notes}`:""}</span></div><strong>{money(p.amount)}</strong><button onClick={()=>void remove("payment",p.id)}>Remove</button></article>)}{!data.payments.length&&<p className="ops-muted">No client payments recorded.</p>}</div></section>
  </div>
 </div>
}
