import Link from "next/link";
import Hero from "@/components/Hero";
import WorkGrid from "@/components/WorkGrid";
import CreatorGrid from "@/components/CreatorGrid";

export default function Home(){return <>
 <Hero/>
 <section id="services" className="home-section home-services"><div className="wrap"><span className="sec-label">// What We Do</span><h2 className="sec-title">Three ways Vira helps brands <span className="accent">earn attention.</span></h2><p className="sec-intro">Strategy, creators and short-form production built around the campaign goal, not a fixed package.</p><div className="service-grid primary-services simplified-services"><div className="service-card featured-service" data-reveal><span className="service-num">01</span><h3>Content Production</h3><p>Hooks, scripts, shoots and edits made for TikTok and Reels, with culture-led copy and creative built for the feed.</p><span className="service-outcome">Brand content · UGC · short-form production</span></div><div className="service-card featured-service" data-reveal><span className="service-num">02</span><h3>Creator Campaigns</h3><p>We source creators who fit the brand, shape the brief and manage the campaign from casting to final post.</p><span className="service-outcome">Creator matching · briefing · campaign management</span></div><div className="service-card featured-service" data-reveal><span className="service-num">03</span><h3>Paid Amplification</h3><p>When the creative works, we help put more reach behind it through paid social and creator-led advertising.</p><span className="service-outcome">Testing · paid reach · creative learning</span></div></div><div className="hero-actions"><Link href="/services" className="btn-ghost">Explore Services →</Link></div></div></section>
 <section id="work" className="home-section"><div className="wrap"><span className="sec-label">// Selected Work</span><h2 className="sec-title">See what Vira can <span className="accent">make.</span></h2><p className="sec-intro">Short-form concepts, creator-led formats and campaign ideas designed to feel native to the feed.</p><WorkGrid/><div className="hero-actions"><Link href="/work" className="btn-ghost">See All Work →</Link></div></div></section>
 <section id="creators" className="creator-section home-section"><div className="wrap"><div className="creator-head"><div><span className="sec-label">// Vira Network</span><h2 className="sec-title">Fit matters more than <span className="accent">follower count.</span></h2></div><p className="sec-intro">Vira works with vetted creators based on personality, audience, format and brand fit, so brands get the right voice for each campaign.</p></div><CreatorGrid/><div className="hero-actions"><Link href="/creators" className="btn-primary">Find Creators Through Vira →</Link><Link href="/creators/apply" className="btn-ghost">Join Vira Network</Link></div></div></section>
 <section id="process" className="home-section home-process"><div className="wrap"><span className="sec-label">// How Campaigns Work</span><h2 className="sec-title">Brief. Build. <span className="accent">Launch.</span></h2><div className="process process-three"><div className="step" data-reveal><span className="step-time">01</span><h4>Brief</h4><p>Tell us the brand, audience, campaign goal and what you need people to do.</p></div><div className="step" data-reveal><span className="step-time">02</span><h4>Build</h4><p>We shape the concept, creators, content and rollout around the brief.</p></div><div className="step" data-reveal><span className="step-time">03</span><h4>Launch & Learn</h4><p>The campaign goes live, we watch the response and use the results to improve what comes next.</p></div></div></div></section>
 <section className="cta-band home-cta"><div className="wrap"><span className="sec-label" style={{justifyContent:'center',display:'flex'}}>// Let&apos;s Talk</span><h2>HAVE A CAMPAIGN IN MIND?</h2><p className="hero-sub">Tell us what you are trying to achieve. We will work out the creators, content and campaign approach from there.</p><div className="hero-actions"><Link href="/contact" className="btn-primary">Start a Campaign →</Link></div><p className="cta-micro">Every campaign is scoped around the brief.</p></div></section>
 </>}
