"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { creatorFormats, niches } from "@/data/site";

type Data = {
  fullName:string; email:string; phone:string; city:string; ageBracket:string; gender:string;
  tiktok:string; tiktokFollowers:string; avgViews:string; instagram:string; instagramFollowers:string; youtube:string; bestContent:string;
  niches:string[]; languages:string; formats:string[];
  brandExperience:string; pastBrands:string; ugc:string; ownAccount:string; paidUsage:string; physicalShoots:string; travel:string; rateRange:string; portfolio:string;
  website:string;
};
const initial:Data={fullName:'',email:'',phone:'',city:'',ageBracket:'',gender:'',tiktok:'',tiktokFollowers:'',avgViews:'',instagram:'',instagramFollowers:'',youtube:'',bestContent:'',niches:[],languages:'',formats:[],brandExperience:'',pastBrands:'',ugc:'',ownAccount:'',paidUsage:'',physicalShoots:'',travel:'',rateRange:'',portfolio:'',website:''};
const labels=['Profile','Platforms','Content','Brand Work','Review'];
export default function CreatorWizard(){
 const [step,setStep]=useState(0),[data,setData]=useState<Data>(initial),[consent,setConsent]=useState(false),[status,setStatus]=useState<'idle'|'sending'|'sent'|'error'|'config'>('idle');
 useEffect(()=>{try{const saved=localStorage.getItem('vira-creator-application-v1');if(saved)setData({...initial,...JSON.parse(saved)})}catch{}},[]);
 useEffect(()=>{if(status!=='sent')localStorage.setItem('vira-creator-application-v1',JSON.stringify(data))},[data,status]);
 const set=(key:keyof Data,value:string|string[])=>setData(v=>({...v,[key]:value}));
 const toggle=(key:'niches'|'formats',value:string)=>set(key,data[key].includes(value)?data[key].filter(v=>v!==value):[...data[key],value]);
 const valid=useMemo(()=>{
   if(step===0)return !!(data.fullName&&data.email&&data.phone&&data.city&&data.ageBracket);
   if(step===1)return !!(data.tiktok&&data.tiktokFollowers);
   if(step===2)return data.niches.length>0&&!!data.languages&&data.formats.length>0;
   if(step===3)return !!(data.brandExperience&&data.ugc&&data.ownAccount&&data.paidUsage&&data.physicalShoots&&data.travel);
   return consent;
 },[step,data,consent]);
 async function submit(e:FormEvent){e.preventDefault();if(!consent)return;setStatus('sending');try{const r=await fetch('/api/creator-application',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(r.ok){setStatus('sent');localStorage.removeItem('vira-creator-application-v1')}else if(j.code==='EMAIL_NOT_CONFIGURED')setStatus('config');else setStatus('error')}catch{setStatus('error')}}
 if(status==='sent')return <div className="form-card form-success"><div className="success-mark">✓</div><h2>Application received.</h2><p>Thanks for applying to the Vira Network. We review applications manually and will contact you if your profile fits current or upcoming campaign needs.</p><a className="btn-primary" href="/creators">Back to Vira Network</a></div>;
 return <form className="form-card" onSubmit={submit}>
  <div className="progress">{labels.map((_,i)=><span className={`progress-step ${i<step?'done':i===step?'active':''}`} key={i}/>)}</div><div className="step-labels">{labels.map((x,i)=><span className={i===step?'active':''} key={x}>{x}</span>)}</div>
  {step===0&&<><h2>About you</h2><p className="form-intro">Start with the details we need to identify and contact you.</p><div className="field-grid"><Field label="Full name *"><input value={data.fullName} onChange={e=>set('fullName',e.target.value)} required/></Field><Field label="Email *"><input type="email" value={data.email} onChange={e=>set('email',e.target.value)} required/></Field><Field label="Phone / WhatsApp *"><input value={data.phone} onChange={e=>set('phone',e.target.value)} required/></Field><Field label="City / town *"><input value={data.city} onChange={e=>set('city',e.target.value)} placeholder="Nairobi, Mombasa, Kisumu…" required/></Field><Field label="Age bracket *"><select value={data.ageBracket} onChange={e=>set('ageBracket',e.target.value)} required><option value="">Select</option><option>18–20</option><option>21–24</option><option>25–29</option><option>30–34</option><option>35+</option></select></Field><Field label="Gender (optional)"><select value={data.gender} onChange={e=>set('gender',e.target.value)}><option value="">Prefer not to say</option><option>Female</option><option>Male</option><option>Other</option></select></Field></div></>}
  {step===1&&<><h2>Your platforms</h2><p className="form-intro">Follower count helps with campaign planning, but it is not the only thing we look at.</p><div className="field-grid"><Field label="TikTok username / URL *"><input value={data.tiktok} onChange={e=>set('tiktok',e.target.value)} placeholder="@username or https://..." required/></Field><Field label="TikTok followers *"><input value={data.tiktokFollowers} onChange={e=>set('tiktokFollowers',e.target.value)} placeholder="e.g. 12,500" required/></Field><Field label="Typical / average views"><input value={data.avgViews} onChange={e=>set('avgViews',e.target.value)} placeholder="Approximate is fine"/></Field><Field label="Instagram username / URL"><input value={data.instagram} onChange={e=>set('instagram',e.target.value)}/></Field><Field label="Instagram followers"><input value={data.instagramFollowers} onChange={e=>set('instagramFollowers',e.target.value)}/></Field><Field label="YouTube / other platform"><input value={data.youtube} onChange={e=>set('youtube',e.target.value)}/></Field><Field label="Link to your best content" full><input type="url" value={data.bestContent} onChange={e=>set('bestContent',e.target.value)} placeholder="A TikTok, Reel or video you're proud of"/></Field></div></>}
  {step===2&&<><h2>Your content</h2><p className="form-intro">Choose the categories and formats that actually feel natural for you.</p><div className="field full"><label>Niches *</label><div className="choice-grid">{niches.map(n=><div className="choice" key={n}><input id={`n-${n}`} type="checkbox" checked={data.niches.includes(n)} onChange={()=>toggle('niches',n)}/><label htmlFor={`n-${n}`}>{n}</label></div>)}</div></div><div className="field full" style={{marginTop:22}}><label>Formats you can create *</label><div className="choice-grid">{creatorFormats.map(n=><div className="choice" key={n}><input id={`f-${n}`} type="checkbox" checked={data.formats.includes(n)} onChange={()=>toggle('formats',n)}/><label htmlFor={`f-${n}`}>{n}</label></div>)}</div></div><div className="field" style={{marginTop:22}}><label>Languages you create in *</label><input value={data.languages} onChange={e=>set('languages',e.target.value)} placeholder="English, Swahili, Sheng…"/></div></>}
  {step===3&&<><h2>Brand work</h2><p className="form-intro">This helps us match you to the right type of brief and usage.</p><div className="field-grid"><YesNo label="Have you worked with brands before? *" value={data.brandExperience} onChange={v=>set('brandExperience',v)}/><YesNo label="Open to UGC-only work? *" value={data.ugc} onChange={v=>set('ugc',v)}/><YesNo label="Open to posting on your own account? *" value={data.ownAccount} onChange={v=>set('ownAccount',v)}/><YesNo label="Open to paid-ad usage / Spark Ads? *" value={data.paidUsage} onChange={v=>set('paidUsage',v)}/><YesNo label="Available for physical shoots? *" value={data.physicalShoots} onChange={v=>set('physicalShoots',v)}/><YesNo label="Open to travel for campaigns? *" value={data.travel} onChange={v=>set('travel',v)}/><Field label="Past brands (optional)" full><textarea value={data.pastBrands} onChange={e=>set('pastBrands',e.target.value)} placeholder="List brands or campaign examples"/></Field><Field label="Typical rate / range"><input value={data.rateRange} onChange={e=>set('rateRange',e.target.value)} placeholder="Optional. e.g. KSh 8K–15K per video"/></Field><Field label="Portfolio / media kit link"><input type="url" value={data.portfolio} onChange={e=>set('portfolio',e.target.value)} placeholder="Google Drive, website, Linktree…"/></Field><div className="honeypot"><input value={data.website} onChange={e=>set('website',e.target.value)} tabIndex={-1}/></div></div></>}
  {step===4&&<><h2>Review & apply</h2><p className="form-intro">Check the important details before you send your application.</p><div className="review-grid"><Review label="Name" value={data.fullName}/><Review label="Location" value={data.city}/><Review label="TikTok" value={`${data.tiktok} · ${data.tiktokFollowers} followers`}/><Review label="Niches" value={data.niches.join(', ')}/><Review label="Formats" value={data.formats.join(', ')}/><Review label="Languages" value={data.languages}/><Review label="UGC" value={data.ugc}/><Review label="Posting" value={data.ownAccount}/></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I confirm the information is accurate and agree that Vira may use it to assess my application and contact me about relevant creator opportunities. Joining the network does not guarantee paid work.</span></label></>}
  <div className="form-actions">{step>0?<button type="button" className="form-button secondary" onClick={()=>setStep(s=>s-1)}>← Back</button>:<span/>}{step<4?<button type="button" className="form-button" disabled={!valid} onClick={()=>setStep(s=>s+1)}>Continue →</button>:<button className="form-button" disabled={!valid||status==='sending'}>{status==='sending'?'Sending…':'Submit application →'}</button>}</div>
  {status==='error'&&<p className="form-error">We could not send the application. Please try again or contact Vira directly.</p>}{status==='config'&&<p className="form-error">Online application delivery is not configured yet. Please contact Vira directly for now.</p>}
 </form>;
}
function Field({label,full=false,children}:{label:string;full?:boolean;children:React.ReactNode}){return <div className={`field ${full?'full':''}`}><label>{label}</label>{children}</div>}
function YesNo({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const key=label.toLowerCase().replace(/[^a-z0-9]+/g,'-');return <fieldset className="field"><legend>{label}</legend><div className="radio-row">{['Yes','No'].map(x=>{const id=`${key}-${x.toLowerCase()}`;return <div className="radio-choice" key={x}><input id={id} type="radio" name={key} checked={value===x} onChange={()=>onChange(x)}/><label htmlFor={id}>{x}</label></div>})}</div></fieldset>}
function Review({label,value}:{label:string;value:string}){return <div className="review-item"><span>{label}</span><strong>{value||'—'}</strong></div>}
